####################
####    Me    ######
####################
[[main]]
name = "Me"
pageRef = "Me"
weight = 20

[[main]]
name = "Certifications"
parent = "Me"
pageRef = "Me/Certifications"
weight = 20

####################
#### Write Up ######
####################
[[main]]
name = "WriteUp"
weight = 30

[[main]]
name = "Machines"
parent = "WriteUp"
pageRef = "WriteUp/Machines/"
weight = 30

#[[main]]
#name = "Red Team Labs"
#parent = "WriteUp"
#pageRef = "WriteUp/RedTeamLabs/"
#weight = 30

#### FOOTER ####
[[footer]]
none = "none"
